services:
  - type: web
    name: talus-server
    runtime: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
